# ASSIGNMENT 3

## Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

## Answer:


In [5]:
import numpy as np
arr=np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

## Question 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

## Answer:

In [19]:
n=5
list1=[]
list2=[]
print("Enter the elements for List 1:")
for i in range(5):
    ele=int(input())
    list1.append(ele)
print("Enter the elements for List 2:")
for j in range(5):
    ele=int(input())
    list2.append(ele)
arr1=np.array(list1)
arr2=np.array(list2)
print("Concatenating the arrays: ")
arr3=np.concatenate((arr1,arr2))
print(arr3)
print("Sorting the array:")
print(np.sort(arr3))

Enter the elements for List 1:
3
4
5
6
7
Enter the elements for List 2:
8
7
4
2
3
Concatenating the arrays: 
[3 4 5 6 7 8 7 4 2 3]
Sorting the array:
[2 3 3 4 4 5 6 7 7 8]


## Question 3:
Write a code snippet to find the dimensions of a ndarray and its size.

## Answer:

In [30]:
arr=np.array([[3,12,55],
             [8,4,3],
             [33,15,78],
             [90,12,44]])
print("Dimension of the array : ",np.ndim(arr))
print("Size of the array : ",np.size(arr))

Dimension of the array :  2
Size of the array :  12


## Question 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

## Answer:

We can convert 1D array into 2D array using:
   * reshape()
   * newaxis()
   * expand_dims()
   

In [44]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D array :")
arr_2d = np.reshape(arr, (2, 5))
print("2D array using reshape() :\n",arr_2d)
arr_2d=arr[np.newaxis,:]
print("2D array using newaxis :\n",arr_2d)
arr_2d=np.expand_dims(arr,axis=0)
print("2D array using expand_dims() :\n",arr_2d)


1D array :
2D array using reshape() :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
2D array using newaxis :
 [[0 1 2 3 4 5 6 7 8 9]]
2D array using expand_dims() :
 [[0 1 2 3 4 5 6 7 8 9]]


## Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.

## Answer:

In [58]:
arr1=np.array([[1,4,5],
      [3,5,8],
      [11,6,33]])
arr2=np.array([[11,34,5],
      [37,55,78],
      [1,16,3]])
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
print("Stacking arrays vertically :\n",np.vstack((arr1,arr2)))
print("Stacking arrays horizontally :\n",np.hstack((arr1,arr2)))

Array 1:
 [[ 1  4  5]
 [ 3  5  8]
 [11  6 33]]
Array 2:
 [[11 34  5]
 [37 55 78]
 [ 1 16  3]]
Stacking arrays vertically :
 [[ 1  4  5]
 [ 3  5  8]
 [11  6 33]
 [11 34  5]
 [37 55 78]
 [ 1 16  3]]
Stacking arrays horizontally :
 [[ 1  4  5 11 34  5]
 [ 3  5  8 37 55 78]
 [11  6 33  1 16  3]]


## Question 6:
How to get unique items and counts of unique items?

## Answer:

In [67]:
arr1=np.array([1,55,3,43,67,22,89,3,55,77,22,89,0,5,55,37,98,3,67,89,98])
print("The array is :\n",arr1)
un,count1=np.unique(arr1,return_counts=True)
print("Unique items in array :\n",un)
print("Number of unique items is :",np.size(count1))

The array is :
 [ 1 55  3 43 67 22 89  3 55 77 22 89  0  5 55 37 98  3 67 89 98]
Unique items in array :
 [ 0  1  3  5 22 37 43 55 67 77 89 98]
Number of unique items is : 12
